### PR TITLE
Updated jquery-svgpan.js and added a test.

### PR DESCRIPTION
**Pull request by erichandsmith**
(The Diff view of the old and new files is kind of funky. Might be easier to just view the updated files.)
Fixed zooming when the SVG isn't full screen.
Fixed zooming when the cursor is over text.
Added reset, zoomIn, and zoomOut button functionality.
Removed some unused code, and converted mousewheel event.

### CODE REVIEW

**Comment by talos** [comment]
Thanks for the pull request! It's a bit tough to review changes with a pull directly into master & GitHub's interface, so I've merged this, but reverted master to how it was and added this to the develop branch.  Once I've reviewed the changes, I'll merge it back into master.

**Comment by talos** [comment]
Unfortunately, I won't be able to merge this into master right now, for the following reasons:
- The addition of button handlers for zoom in/out/reset changes the API signature and breaks the existing example file.  I think a better approach, rather than baking "click" handlers into the plugin, would be to define events that can be triggered externally upon the element.
- The changes introduce a dependency upon jquery-mousewheel, which was not included in the pull request.
- The example refers to several script files in a "../scripts" folder  [jQuery and the mousewheel plugin].

I could merge in these changes (the zoom fixes) if you reintroduce the pull request without the changed API signature, example file, or dependency upon the other plugin.

Thanks!

**Comment by erichandsmith** [comment]
Hello, John,

The only big changes would be the following (everything else can be
ignored, 'cause I was just fiddlin' around):

getEventPoint = function (event) {
    var p = root.createSVGPoint();
-    p.x = event.offsetX;
  p.y = event.offsetY;
-    return p;
  }

And this in the handleMouseWheel function (to handle zoom funkiness over
text elements):

if (event.originalEvent.target.nodeType === 3) {
    p.x = $(event.target).position().left - $root.position().left;
    p.y = $(event.target).position().top - $root.position().top;
    p = p.matrixTransform(gViewport.getCTM().inverse());
    p.x += event.offsetX;
    p.y += event.offsetY;
}

You'll have to change the names of things back to what you originally used,
like gViewport.  I changed some names to better understand what was going
on.

Please forgive me, too, because this is my first foray into javascript.
Thank you.

Kind Regards,
Eric

**Comment by talos** [comment]
No worries -- thanks for isolating these changes out!

Could you please describe what the funkiness was when zooming over text?  I just want to understand the problem before making the change there.

Thanks again,
-John

**Comment by erichandsmith** [comment]
In Google Chrome, the event comes from the Text node, not from the
SVGTextElement.  So, the mouse cordinates are based on the Text node, not
the root SVG element.

In IE9, the event comes from the SVGTextElement, so the coordinates are
based on the root SVG element.

I haven't tested FireFox or Safari, or other versions of IE, though...

Kind Regards,
Eric

**Comment by erichandsmith** [comment]
Hello, John,

Just discovered that a <tspan> inside a <text> messes up the mouse
coordinates reported by the event even more.  Back to the drawing board...

Kind Regards,
Eric

**Comment by saamalam** [comment]
I've used SVGPan.js and while dragging the objects in zoom out mode the mouse coordinate loses balance with those with objects which i'm dragging.

So can you help me out with it.

**Pull request merged**
